"""Pre-written narrative pool. Placeholders: {char}, {target}, {biome}, {material}, {enemy}, {skill}, {item}.

10 variants per outcome per action-family. Outcome tiers: 1..6."""
from __future__ import annotations

import random


# ---------- HUNT ----------
HUNT: dict[int, list[str]] = {
    1: [  # critical fail
        "The {target} tears into {char}'s side. Blood on the grass, a scream on the wind.",
        "A snapping branch gives {char} away. The {target} strikes first — and hard.",
        "{char}'s foot slips. The {target} is on them before they draw steel.",
        "The trap fails. The {target} circles behind and takes a savage bite.",
        "{char} misjudges the wind. The {target} charges — knocking them into the dirt.",
        "A hidden thorn tears {char}'s hand. The {target} takes the opening.",
        "{char}'s bowstring snaps at the worst moment. The {target} closes the distance in a heartbeat.",
        "The {target} is not alone. Two more emerge from the brush — {char} barely escapes.",
        "{char} freezes for a breath too long. The {target} answers with claw and fang.",
        "The ground gives way — {char} tumbles into the {target}'s hunting nest.",
    ],
    2: [  # fail with bad effect (status)
        "The {target} escapes into the brush, but not before leaving {char} bleeding.",
        "{char} misses the killing strike. The {target} counters — a shallow wound, deep pain.",
        "The chase leaves {char} exhausted and empty-handed. Something feels wrong afterwards.",
        "{char}'s arrow lands wide. The {target} vanishes; the wound in {char}'s leg does not.",
        "A ragged fight ends with the {target} gone and {char} nursing an injured arm.",
        "The {target} slips the trap and gores {char} on the way past.",
        "{char} loses the trail and returns with a fever from tainted water.",
        "The {target} bites and flees. The venom sinks in slow.",
        "{char} stumbles into poison ivy while stalking the {target}. Everything itches.",
        "The {target} outruns {char} — into a patch of stinging nettles that leave welts.",
    ],
    3: [  # fail (no status)
        "The {target} slips into the tall grass and is gone.",
        "{char} loses the trail after an hour of stalking. Nothing.",
        "The {target} was here — the tracks are fresh — but the beast is long gone.",
        "{char}'s shot goes wide. The {target} bolts into the treeline.",
        "A crow calls out. The {target} disappears before {char} can even nock an arrow.",
        "{char} returns empty-handed but wiser. The {target} is not so easily caught.",
        "The {target}'s trail crosses a river. {char} cannot pick it up on the far bank.",
        "{char} circles for hours. The {target} was hunting them the whole time — playing.",
        "The wind shifts. The {target} catches the scent and vanishes.",
        "{char} finds the {target}'s den — but it is empty.",
    ],
    4: [  # success with bad effect
        "{char} slays the {target} — but not before a fang finds their thigh.",
        "The {target} falls. {char} kneels, breathing hard, blood soaking their sleeve.",
        "A brutal fight. {char} wins, but limps home with a swollen wrist.",
        "The {target} is dead. So is {char}'s pride — that scar will not soon fade.",
        "{char} takes the kill and a nasty cut to the cheek in the same swing.",
        "The {target} dies with its teeth still in {char}'s boot. Poison seeps through the leather.",
        "{char} wins — but the {target}'s last thrash cracks a rib.",
        "The kill is clean; {char}'s hand is not. Something in the beast's blood burns.",
        "{char} triumphs, but the {target}'s claws leave a mark that itches for days.",
        "Victory. And a sprained ankle from the last frantic leap.",
    ],
    5: [  # success
        "{char} drops the {target} with a well-placed strike. The forest goes quiet.",
        "A clean hunt. The {target} never saw {char} coming.",
        "One arrow. One breath. The {target} falls.",
        "{char} moves in the wind's shadow and takes the {target} without effort.",
        "The {target} dies quickly under {char}'s blade.",
        "{char} follows the tracks patiently — and is rewarded. The {target} is theirs.",
        "The kill is unspectacular but sure. {char} slings the {target} over their shoulder.",
        "A single decisive strike ends the {target}.",
        "{char} times the trap perfectly. The {target} never had a chance.",
        "The forest yields. The {target} lies still at {char}'s feet.",
    ],
    6: [  # critical success
        "In one impossible motion, {char} takes the {target} — and its mate, hidden in the brush!",
        "A perfect hunt. The {target} falls, and {char} finds a hidden cache nearby.",
        "{char} moves like a memory. The {target} is dead before the leaves stop rustling. Fortune smiles.",
        "The {target} falls with a rare pelt intact — a masterful kill.",
        "{char} strikes true. The {target} dies, and something glints in the grass beside it.",
        "A hunter's tale for the taverns. The {target} is theirs — and something rarer besides.",
        "The kill is so clean the local villagers will pay double for the pelt.",
        "{char} slays the {target} without a sound. The wind itself seems to approve.",
        "One shot. One kill. And a skillbook wrapped in oilcloth beneath the {target}'s den.",
        "The {target} dies at {char}'s hand and the crows scatter — clearing the way to a hidden trove.",
    ],
}


# ---------- GATHER ----------
GATHER: dict[int, list[str]] = {
    1: [
        "{char} disturbs a nest of stinging wasps. The {material} is forgotten in the panic.",
        "The {material} vein collapses. {char}'s hand is caught in the fall.",
        "A hidden root snares {char}'s ankle. The gathering basket spills into a fast stream.",
        "{char} reaches for the {material} and finds something with teeth reaching back.",
        "The ground gives way — {char} tumbles into cold mud, empty-handed.",
        "A jealous crow steals {char}'s pouch mid-work.",
        "{char} mistakes toxic {material} for the real thing and pays for it.",
        "The tools break. The pouch tears. Nothing goes right today.",
        "A sudden rain washes away {char}'s carefully-marked spot.",
        "{char} slices their palm open on a sharp stone. All gathering must stop.",
    ],
    2: [
        "{char} gathers little, and a rash spreads across their forearm from the {material}'s sap.",
        "The {material} yields nothing worthwhile — and something in the soil makes {char} queasy.",
        "A slow, unproductive hour. {char} leaves with a splinter that will not stop throbbing.",
        "Wet ground, wet clothes, chilled to the bone. {char} finds nothing of note.",
        "{char} disturbs a hornets' nest. Bites but no {material}.",
        "The {material} is scarce. {char} returns with a shallow cut that will scar.",
        "A slippery step ends in a twisted ankle. The {material} eludes them.",
        "{char} finds a snake instead of {material}. It bites.",
        "The gathering fails. The blisters do not.",
        "{char} inhales the wrong pollen and coughs the rest of the day.",
    ],
    3: [
        "{char} searches for hours. The {material} is not here today.",
        "The vein of {material} is spent. Better luck elsewhere.",
        "A wasted afternoon. {char} pockets nothing worth carrying.",
        "The {material} seems to hide from {char} today.",
        "Whatever grew here has been taken already.",
        "{char} maps the area for future returns, but leaves empty-handed.",
        "The {material} is here but too immature to harvest.",
        "{char} finds only twigs and stones in place of the {material} they sought.",
        "Rain drives {char} back before they can find any {material}.",
        "The wind pushes {char} off-course. No {material} today.",
    ],
    4: [
        "{char} gathers a modest amount of {material}, but the effort leaves them aching.",
        "The {material} is good — but the thorns leave {char}'s hands red and raw.",
        "A decent haul, at the cost of a bee sting that swells all afternoon.",
        "{char} bags the {material} but leaves a boot behind in the mud.",
        "Some {material} for the pouch, and a splinter in {char}'s thumb for the road.",
        "The gathering goes well until {char} slips and lands in a patch of poison-leaf.",
        "{char} fills the pouch with {material} but pulls a muscle doing it.",
        "A reasonable harvest — with a mild fever taking hold by dusk.",
        "The {material} is theirs. So is the thorn buried deep in {char}'s palm.",
        "{char} bags the {material} but the exertion leaves them light-headed.",
    ],
    5: [
        "{char} fills the pouch with fine {material}. A steady day's work.",
        "The {material} yields well. {char} makes good time returning.",
        "A patient gatherer is a rich one. {char} leaves with pockets heavy with {material}.",
        "{char} finds a rich patch of {material} and harvests it clean.",
        "The {material} is where {char} expected it to be. Success.",
        "A quiet, productive gather. The {material} was generous.",
        "{char} works methodically. The {material} accumulates.",
        "Every step yields more {material}. {char} smiles for the first time all week.",
        "{char} identifies a hidden growth of {material} and takes their fill.",
        "The {material} is fine quality. {char} will trade well tonight.",
    ],
    6: [
        "{char} discovers a hidden vein of pure {material} — a fortune in a single sitting!",
        "A jackpot. The {material} is dense, rich, and untouched. {char} nearly cannot carry it all.",
        "{char} finds {material} of legendary quality — and a small carved token beside it.",
        "The soil practically offers up the {material}. {char} leaves with more than double the expected haul.",
        "A perfect gathering. {char} finds a cache someone hid long ago among the {material}.",
        "{char} stumbles on rare {material} growing beside the common. Both go in the pouch.",
        "The {material} is exceptional today. {char} may need to make two trips.",
        "A stranger's forgotten bundle of {material} sits under a stone. {char} claims it.",
        "The {material} sings under {char}'s hands. A crafter would weep for such quality.",
        "{char} finds {material} and a small polished stone — worth more than a week's gather.",
    ],
}


# ---------- EXPLORE ----------
EXPLORE: dict[int, list[str]] = {
    1: [
        "{char} steps into the {biome} — and into a pitfall waiting for the unwary.",
        "A pack of hunters mistake {char} for prey. The chase is long.",
        "{char} is caught in a sudden storm in the {biome}. Lightning splits a tree nearby.",
        "The {biome} yields nothing but sinking mud that swallows {char}'s pouch.",
        "{char} is bitten by something they never see.",
        "The path in the {biome} leads {char} in a wide, exhausted circle.",
        "A false trail. A cursed stone. {char} feels their luck sour.",
        "The {biome} takes more from {char} than it gives — much more.",
        "{char} disturbs an ancient marker. The air grows heavy.",
        "The {biome} is haunted today. {char} leaves rattled and bloody.",
    ],
    2: [
        "The {biome} is quiet. Too quiet. {char} returns tense and short of breath.",
        "{char} wanders the {biome} for hours and leaves with a limp.",
        "A grim day in the {biome}. Nothing found, and a chill that will not shake.",
        "The {biome} tests {char} — a scraped shin and empty pockets.",
        "{char} steps in something venomous. The poison will pass. Slowly.",
        "The {biome} offers nothing but a nasty scratch and a sense of being watched.",
        "{char} returns from the {biome} with a fever taking hold.",
        "The path in the {biome} circles back on itself. {char} loses time and strength.",
        "A wrong turn in the {biome} costs {char} a full waterskin.",
        "The {biome} takes a toll: a sprain, a bruise, and no discovery.",
    ],
    3: [
        "{char} maps a portion of the {biome} but finds nothing of note.",
        "A quiet walk. The {biome} shares no secrets today.",
        "{char} returns from the {biome} without incident and without discovery.",
        "The {biome} sleeps. So does {char}, for a time, before returning.",
        "Nothing today. But {char} learns the shape of the land better.",
        "The {biome} is much as it was described. No more, no less.",
        "{char} spots signs of others, but no others themselves.",
        "The wind is fair in the {biome}. The purse remains light.",
        "A pleasant walk yields no reward.",
        "{char} finds a fine spot to rest — and only that.",
    ],
    4: [
        "{char} finds a strange marker in the {biome} — and a nasty gash from prying it loose.",
        "A hidden cache in the {biome} — but a splinter now festers in {char}'s hand.",
        "{char} uncovers a fragment of an old map, at the cost of a swollen knee.",
        "A small find in the {biome}, followed by a chill that will not leave.",
        "The {biome} rewards {char} — and marks them. A scar to remember.",
        "{char} finds a curiosity and a rash from touching the wrong leaf.",
        "A worthwhile day in the {biome} — save for the bee sting on {char}'s brow.",
        "The {biome} yields a modest treasure and a lingering ache.",
        "{char} discovers something interesting. Something in the water is also interested in {char}.",
        "A partial success. {char} finds coin, and something with teeth finds them.",
    ],
    5: [
        "{char} maps a fine path through the {biome} and finds a modest cache.",
        "A steady exploration. The {biome} yields small but useful discoveries.",
        "{char} discovers a hidden clearing in the {biome} — untouched, peaceful, rewarding.",
        "The {biome} opens up under {char}'s patient tread.",
        "A good day. {char} returns with pockets heavier than they left.",
        "{char} finds a curious carving in the {biome} — and pockets a small pouch of coin nearby.",
        "The {biome} is generous today. {char} learns and gathers in equal measure.",
        "{char} follows an old trail to a small, useful discovery.",
        "The exploration is fruitful. The {biome} remembers those who walk with respect.",
        "{char} spots a hidden trail — and follows it to a small, worthwhile find.",
    ],
    6: [
        "{char} uncovers a lost shrine in the {biome} — and its long-forgotten offering!",
        "A stranger left a chest in the {biome} decades ago. {char} finds it today.",
        "The {biome} reveals a hidden trail leading to a rare relic!",
        "A vein of ancient magic pulses beneath {char}'s feet — and rewards the finder.",
        "{char} steps through a hidden veil in the {biome}. What lies beyond is worth telling for years.",
        "A legendary discovery in the {biome}. The tavern-songs will remember {char}'s name.",
        "{char} finds a skillbook wedged inside a hollow tree. Fortune indeed.",
        "The {biome} opens itself entirely. {char} returns with treasure and story alike.",
        "An old warrior's cache. Weapons, coin, and a map to something greater.",
        "{char} finds a relic shard resting on a mossy stone. It hums when held.",
    ],
}


# ---------- FISH ----------
FISH: dict[int, list[str]] = {
    1: ["The line snaps. Something large is on the other end — and it is coming for {char}."] * 10,
    2: ["A cold day at the water. The line breaks. {char} slips on the wet stone."] * 10,
    3: ["The fish are not biting today."] * 10,
    4: ["{char} catches a fine river fish — and slips on the way back, twisting an ankle."] * 10,
    5: ["A steady catch. {char} lands two river fish and a fistful of river stone."] * 10,
    6: ["{char} pulls up a chest tangled in weeds — coin, an old blade, and a strange scale!"] * 10,
}


# ---------- LOOT RUINS ----------
LOOT_RUINS: dict[int, list[str]] = {
    1: [
        "{char} steps on a pressure-plate. The trap fires — barely dodged, but bleeding.",
        "A cursed altar drains {char}'s strength. The ruins keep their secrets.",
        "The wall collapses. {char} escapes with a broken finger.",
        "A ghast wails from the dark. {char} flees empty-handed and shaken.",
        "The floor gives way under {char}. A long fall. A longer climb back up.",
        "{char} disturbs something old. It disturbs them back.",
        "A poisoned dart takes {char} in the arm. The chamber is picked clean anyway.",
        "The ruins reject {char} today. Blood, no coin.",
        "A false step, a triggered blade. {char} limps home.",
        "The dust seals {char}'s throat. They cough for days.",
    ],
    2: [
        "{char} finds only broken pottery — and a slow-acting curse.",
        "The ruins yield nothing. A shadow follows {char} home.",
        "{char} finds a locked chest but breaks the pick — and their wrist.",
        "A room half-collapsed. {char} explores it and pays with a bruised rib.",
        "The ruin's air is foul. {char} carries the sickness for a week.",
        "A near-miss with a poisoned arrow. Nothing to show for it.",
        "{char} finds a pouch — empty. And a scratch that will not heal quickly.",
        "The ghast's whisper follows {char} out. Sleep will be uneasy.",
        "A trap grazes {char}. The chamber is bare.",
        "{char} disturbs a warding rune. A slight burn. Nothing more.",
    ],
    3: [
        "The ruins hold nothing but dust today.",
        "{char} searches every corner. Empty.",
        "The chambers have been picked clean before {char} arrived.",
        "A quiet exploration. Nothing found.",
        "{char} maps the ruin and leaves.",
        "Old bones, older silence. No treasure.",
        "The ruin is a labyrinth of nothing.",
        "{char} finds a scrap of parchment — illegible.",
        "The traps are all sprung. The rooms are all empty.",
        "Nothing today. But {char} learns the layout.",
    ],
    4: [
        "{char} pries open a chest — a fine relic, and a slice across the palm.",
        "A rare find in the ruins, purchased with a nasty gash.",
        "{char} takes a small relic and a lingering shiver.",
        "The chamber yields treasure and a cursed status that will pass in time.",
        "A relic shard, and a burn on {char}'s wrist from a trap half-triggered.",
        "{char} finds coin and something like an itch that will not go.",
        "The ruin gives, but also takes. Blood for gold.",
        "A modest haul with a wound to match.",
        "{char} loots a chamber and stumbles into a poison mist on the way out.",
        "A relic, a scar, and a story worth telling.",
    ],
    5: [
        "{char} finds a chamber untouched — coin, a fine blade, and a scroll or two.",
        "The ruin rewards patient hands. A steady haul.",
        "{char} loots a small chest cleanly and leaves without waking the dust.",
        "A quiet, profitable delve into the ruins.",
        "{char} finds a stash tucked behind a loose stone.",
        "A skilled explorer's day. The ruins yield what they can.",
        "{char} recovers a relic shard from a shattered urn.",
        "The chambers reveal their offerings to {char} without protest.",
        "A steady loot: coin, a shard, a bit of old silver.",
        "The ruin remembers those who tread with care. Fair trade.",
    ],
    6: [
        "{char} discovers the sealed inner sanctum — a legendary find!",
        "A chamber untouched since the fall of the old kingdom. {char} loots it in awed silence.",
        "The floor cracks open — a hidden vault beneath! Riches beyond expectation.",
        "{char} finds a full skillbook among the bones of a long-dead scholar.",
        "A relic of the old kings — and {char} is the first to touch it in centuries.",
        "The ruin opens itself utterly. {char} carries away more than they thought possible.",
        "A masterwork blade, a chest of coin, and a skillbook. A hero's haul.",
        "{char} steps into a room untouched by time. Everything is theirs.",
        "The whispering ghast leads {char} to a treasure it can no longer use.",
        "A legendary discovery. The bards will tell of {char}'s ruin-delve for a generation.",
    ],
}


# ---------- COMBAT ----------
COMBAT_ATTACK: dict[int, list[str]] = {
    1: [
        "{char}'s blade turns in the strike. The {enemy} answers with a devastating counter.",
        "A misstep! The {enemy} sidesteps and drives a fist into {char}'s ribs.",
        "{char} overextends. The {enemy} takes the opening and does not waste it.",
        "The {enemy} reads {char}'s movement — and punishes it.",
        "{char} strikes and misses. The {enemy} does not.",
        "A wild swing. The {enemy} counters with brutal precision.",
        "{char}'s footing fails at the worst moment. The {enemy} laughs.",
        "The {enemy} slips {char}'s blade and answers with steel.",
        "{char} attacks — and stumbles into a devastating counter.",
        "A critical fumble. The {enemy} punishes it savagely.",
    ],
    2: [
        "{char} lands a glancing blow. The {enemy} responds with a wound {char} will remember.",
        "The strike lands, but the {enemy}'s claws find {char} in return.",
        "A trade of blows — poorly. {char} takes the worse of it.",
        "{char} draws blood, then bleeds more of their own.",
        "The exchange leaves {char} standing, but only just.",
        "A tolerable strike, followed by a stinging retaliation.",
        "{char}'s blade nicks the {enemy}. The {enemy}'s teeth find {char}'s arm.",
        "{char} attacks and pays the price with a shallow gash.",
        "A poor exchange for {char}. The {enemy} presses hard.",
        "The blade lands. So does the {enemy}'s poison-tipped claw.",
    ],
    3: [
        "{char}'s blade whistles past the {enemy}, harmless.",
        "The {enemy} slips the strike. No damage on either side.",
        "A cautious probe. Neither {char} nor the {enemy} gains ground.",
        "The strike is deflected. The pause is heavy.",
        "{char} tests the {enemy}'s defence. Nothing gives.",
        "A wide arc. The {enemy} steps back and studies {char}.",
        "The blade grazes armor. Nothing more.",
        "{char} misses. The {enemy} misses. Reset.",
        "A cautious dance. No blood drawn.",
        "The two circle. No opening presents itself.",
    ],
    4: [
        "{char} lands a solid strike — but the {enemy}'s counter draws blood.",
        "A clean hit! The {enemy} howls, then lashes back before {char} can retreat.",
        "The blade bites. The {enemy}'s claws bite back.",
        "{char} takes ground and pays for it in blood.",
        "A good strike. A worse counter.",
        "The {enemy} staggers, then answers with a stinging blow.",
        "{char} lands and takes a hit. Even exchange, but the wound is real.",
        "A ringing strike, then a graze that will bruise for days.",
        "Blood on both blades now.",
        "{char} draws blood and receives a savage bite in return.",
    ],
    5: [
        "{char}'s strike lands clean. The {enemy} reels.",
        "A crisp hit! The {enemy} bleeds; {char} does not.",
        "{char} times the strike perfectly. The {enemy} staggers.",
        "A well-placed blow. The {enemy} is worse for it.",
        "{char} drives the {enemy} back a full step.",
        "The blade finds home. The {enemy} snarls in pain.",
        "A confident strike. {char} controls the exchange.",
        "The {enemy}'s defence cracks under {char}'s pressure.",
        "{char} lands the blow they intended. Clean.",
        "The strike is exactly where {char} meant it. The {enemy} feels every inch of it.",
    ],
    6: [
        "A masterful strike! The {enemy} reels — {char} presses for the kill!",
        "{char} finds the perfect opening. The {enemy}'s guard shatters entirely.",
        "One blade, one moment. The {enemy} takes a wound they cannot ignore.",
        "A blow of legend. The {enemy} staggers, half-dead already.",
        "{char} moves like flowing water. The {enemy} is broken open.",
        "The {enemy}'s armor cracks under {char}'s precision.",
        "A critical strike! The {enemy}'s knees buckle.",
        "{char} lands a devastating blow. Blood soaks the ground.",
        "The perfect angle, the perfect force. The {enemy} is nearly done.",
        "{char} strikes with impossible speed — the {enemy} nearly falls in one blow!",
    ],
}


# ---------- CRAFT ----------
CRAFT: dict[int, list[str]] = {
    1: [
        "The forge sparks wrong. The {item} shatters — materials lost.",
        "{char}'s hand slips. The {item} is ruined and so are the components.",
        "A miscalculation. The {item} melts into slag.",
        "The bench collapses mid-work. Everything is lost.",
        "A critical failure. The {item} explodes on the anvil.",
        "The components react badly. {char} loses more than they meant to.",
        "The forge is haunted today. The {item} is ash.",
        "{char} miscasts the runes. The {item} crumbles.",
        "A total loss. The {item} is scrap.",
        "The workshop is a disaster. Nothing was made.",
    ],
    2: [
        "The {item} comes out warped. Its edges will not hold true.",
        "A crude {item}. Better than nothing, but only just.",
        "The workmanship is poor. The {item} is barely usable.",
        "The forge yields a crude {item}. {char} sighs at the sight.",
        "The {item} is functional — barely. It will not last.",
        "A rough day at the bench. The {item} is crude.",
        "The materials fought the work. The {item} shows it.",
        "A crude piece. The next attempt must be better.",
        "The {item} is passable, no more.",
        "A learning failure. The crude {item} at least won't break immediately.",
    ],
    3: [
        "The {item} is crude but usable.",
        "A rough {item}. It will serve.",
        "The work is honest but plain. The {item} takes shape.",
        "The {item} is not beautiful, but it functions.",
        "{char} completes the {item} without flourish.",
        "A journeyman's work. The {item} will do.",
        "The {item} is complete. It will not draw praise.",
        "Steady work. Ordinary {item}. Ordinary outcome.",
        "A simple day at the bench. A simple {item} to show for it.",
        "The {item} is finished. Nothing remarkable.",
    ],
    4: [
        "{char} crafts a fine {item} — but suffers a minor burn from the forge.",
        "A fine {item}, forged with a bit of blood from a slipped hammer.",
        "The {item} is fine. {char}'s bandaged thumb tells the rest of the story.",
        "A fine result, though {char}'s eyes burn from the smoke.",
        "The {item} is well-made. {char} will feel the ache in their shoulders tomorrow.",
        "Fine work. A twisted wrist to match.",
        "The {item} comes out fine, at the cost of a cracked nail.",
        "A fine piece. A hot forge left {char} light-headed.",
        "The {item} is worth trading — {char}'s aching hands, less so.",
        "A fine {item}. A minor injury to remember it by.",
    ],
    5: [
        "{char} forges a fine {item}. Solid, sharp, dependable.",
        "A fine {item} takes shape under {char}'s steady hands.",
        "The {item} is fine work — worthy of any market.",
        "A well-crafted {item}. {char} is pleased with the balance.",
        "The forge sings today. The {item} is fine.",
        "{char} completes a fine {item} without incident.",
        "A fine piece. Buyers will pay honest coin.",
        "The {item} is fine — the kind of work that builds a reputation.",
        "Fine craftsmanship. The {item} is ready for a warrior's hand.",
        "A fine {item}, finished cleanly.",
    ],
    6: [
        "A masterwork {item}! The runes hum, the edge sings — a legendary piece.",
        "{char} crafts a masterwork {item}. Word will spread.",
        "The forge yields a masterwork. The {item} radiates quality.",
        "{char}'s hands move as if guided by an old god. Masterwork {item} complete.",
        "A masterwork piece. The {item} will outlast its wielder.",
        "The {item} is masterwork. Nobles will bid for it.",
        "A perfect craft. The {item} is masterwork — a piece for legend.",
        "The {item} is masterwork. The forge itself seems proud.",
        "Masterwork! The {item} is finer than anything {char} has made.",
        "A masterwork {item} — {char} could sell it for a small fortune.",
    ],
}


NARRATIVES: dict[str, dict[int, list[str]]] = {
    "hunt": HUNT,
    "gather": GATHER,
    "explore": EXPLORE,
    "fish": FISH,
    "loot_ruins": LOOT_RUINS,
    "combat_attack": COMBAT_ATTACK,
    "craft": CRAFT,
}


def pick_narrative(action_key: str, outcome: int, **subs) -> str:
    pool = NARRATIVES.get(action_key, {}).get(outcome, ["…"])
    template = random.choice(pool)
    for k, v in subs.items():
        template = template.replace("{" + k + "}", str(v))
    return template
