"""Rune system — 50+ runes dropped by any monster in any continent.
Each rune gives a flat bonus to a specific effect when socketed into an item.
Runes are the monster-drop upgrade path (gems are the marketplace path).
Rune rarity ranges from rare to legendary, with higher rarity granting stronger effects.
"""
from __future__ import annotations

# ============================================================
# Runes — 50 types, each gives +1% (0.01) to a bonus effect
# ============================================================
RUNES: list[dict] = [
    # --- Combat: Offensive (1% each) ---
    {"id": "rune_lifesteal",        "name": "Rune of Vampirism",   "effect_type": "lifesteal",        "value": 0.01,
     "desc": "A blood-etched rune. +1% Lifesteal when socketed."},
    {"id": "rune_crit_chance",      "name": "Rune of Precision",   "effect_type": "crit_chance",      "value": 0.01,
     "desc": "A crosshair-carved rune. +1% Crit chance when socketed."},
    {"id": "rune_crit_damage",      "name": "Rune of Fury",        "effect_type": "crit_damage",      "value": 0.01,
     "desc": "A flame-scorched rune. +1% Crit damage when socketed."},
    {"id": "rune_armor_pen",        "name": "Rune of Piercing",    "effect_type": "armor_pen",        "value": 0.01,
     "desc": "A spear-point rune. +1% Armor penetration when socketed."},
    {"id": "rune_magic_pen",        "name": "Rune of Spell Pen",   "effect_type": "magic_pen",        "value": 0.01,
     "desc": "A rift-carved rune. +1% Magic penetration when socketed."},
    {"id": "rune_physical_amp",     "name": "Rune of Might",       "effect_type": "physical_amp",     "value": 0.01,
     "desc": "A fist-impressed rune. +1% Physical damage when socketed."},
    {"id": "rune_magical_amp",      "name": "Rune of Arcana",      "effect_type": "magical_amp",      "value": 0.01,
     "desc": "A star-charted rune. +1% Magical damage when socketed."},
    {"id": "rune_fire_amp",         "name": "Rune of Flame",       "effect_type": "fire_amp",         "value": 0.01,
     "desc": "A fire-glowing rune. +1% Fire damage when socketed."},
    {"id": "rune_ice_amp",          "name": "Rune of Frost",       "effect_type": "ice_amp",          "value": 0.01,
     "desc": "A frost-rimed rune. +1% Ice damage when socketed."},
    {"id": "rune_poison_amp",       "name": "Rune of Venom",       "effect_type": "poison_amp",       "value": 0.01,
     "desc": "A bile-stained rune. +1% Poison damage when socketed."},
    {"id": "rune_lightning_amp",    "name": "Rune of Storm",       "effect_type": "lightning_amp",    "value": 0.01,
     "desc": "A crackling rune. +1% Lightning damage when socketed."},
    {"id": "rune_attack_speed",     "name": "Rune of Haste",       "effect_type": "action_speed",     "value": 0.01,
     "desc": "A wind-carved rune. +1% Action speed when socketed."},
    {"id": "rune_strike_bonus",     "name": "Rune of Striking",    "effect_type": "strike_accuracy",  "value": 0.01,
     "desc": "A target-marked rune. +1% Strike accuracy when socketed."},

    # --- Combat: Defensive (1% each) ---
    {"id": "rune_evade_bonus",      "name": "Rune of Evasion",     "effect_type": "evasion",          "value": 0.01,
     "desc": "A shadow-flickered rune. +1% Evasion when socketed."},
    {"id": "rune_armor_bonus",      "name": "Rune of Warding",     "effect_type": "armor_bonus_pct",  "value": 0.01,
     "desc": "A shield-engraved rune. +1% Armor bonus when socketed."},
    {"id": "rune_magic_resist",     "name": "Rune of Resistance",  "effect_type": "magic_resist_pct", "value": 0.01,
     "desc": "A ward-circle rune. +1% Magic resistance when socketed."},
    {"id": "rune_hp_regen",         "name": "Rune of Regeneration","effect_type": "hp_regen_pct",     "value": 0.01,
     "desc": "A heart-pulse rune. +1% HP regen per turn when socketed."},
    {"id": "rune_mp_regen",         "name": "Rune of Mana Flow",   "effect_type": "mp_regen_pct",     "value": 0.01,
     "desc": "A stream-carved rune. +1% MP regen per turn when socketed."},
    {"id": "rune_stamina_regen",    "name": "Rune of Endurance",   "effect_type": "stamina_regen_pct","value": 0.01,
     "desc": "A drum-beat rune. +1% Stamina regen when socketed."},
    {"id": "rune_thorns",           "name": "Rune of Reflection",  "effect_type": "thorns",           "value": 0.01,
     "desc": "A spike-barbed rune. +1% Damage reflect when socketed."},
    {"id": "rune_max_hp",           "name": "Rune of Vitality",    "effect_type": "max_hp_pct",       "value": 0.01,
     "desc": "A heartstone rune. +1% Max HP when socketed."},
    {"id": "rune_max_mp",           "name": "Rune of Mana Pool",   "effect_type": "max_mp_pct",       "value": 0.01,
     "desc": "A wellspring rune. +1% Max MP when socketed."},
    {"id": "rune_max_stamina",      "name": "Rune of Vigor",       "effect_type": "max_stamina_pct",  "value": 0.01,
     "desc": "A lung-breath rune. +1% Max Stamina when socketed."},

    # --- Status Resistance (1% each) ---
    {"id": "rune_resist_stun",      "name": "Rune of Steadfast",   "effect_type": "status_resist_stun",     "value": 0.01,
     "desc": "A pillar rune. +1% Stun resist when socketed."},
    {"id": "rune_resist_bleed",     "name": "Rune of Clotting",    "effect_type": "status_resist_bleed",    "value": 0.01,
     "desc": "A blood-drop rune. +1% Bleed resist when socketed."},
    {"id": "rune_resist_poison",    "name": "Rune of Purity",      "effect_type": "status_resist_poison",   "value": 0.01,
     "desc": "A clear-water rune. +1% Poison resist when socketed."},
    {"id": "rune_resist_burn",      "name": "Rune of Fireproof",   "effect_type": "status_resist_burn",     "value": 0.01,
     "desc": "A charred rune. +1% Burn resist when socketed."},
    {"id": "rune_resist_chill",     "name": "Rune of Warmth",      "effect_type": "status_resist_chill",    "value": 0.01,
     "desc": "A hearth rune. +1% Chill/freeze resist when socketed."},
    {"id": "rune_resist_shock",     "name": "Rune of Grounding",   "effect_type": "status_resist_shock",    "value": 0.01,
     "desc": "A root-tree rune. +1% Shock resist when socketed."},
    {"id": "rune_resist_fear",      "name": "Rune of Courage",     "effect_type": "status_resist_fear",     "value": 0.01,
     "desc": "A lion-head rune. +1% Fear/shaken resist when socketed."},
    {"id": "rune_resist_weary",     "name": "Rune of Vigor",       "effect_type": "status_resist_weary",    "value": 0.01,
     "desc": "A sun-rise rune. +1% Weary resist when socketed."},
    {"id": "rune_resist_ensnare",   "name": "Rune of Freedom",     "effect_type": "status_resist_ensnare",  "value": 0.01,
     "desc": "A broken-chain rune. +1% Ensnare resist when socketed."},
    {"id": "rune_resist_blind",     "name": "Rune of Sight",       "effect_type": "status_resist_blind",    "value": 0.01,
     "desc": "An open-eye rune. +1% Blind resist when socketed."},

    # --- Status Application (1% each) ---
    {"id": "rune_apply_bleed",      "name": "Rune of Bloodletting","effect_type": "apply_bleed",      "value": 0.01,
     "desc": "A blood-letter rune. +1% chance to apply Bleeding on hit."},
    {"id": "rune_apply_poison",     "name": "Rune of Toxic",       "effect_type": "apply_poison",     "value": 0.01,
     "desc": "A venom-drip rune. +1% chance to apply Poison on hit."},
    {"id": "rune_apply_burn",       "name": "Rune of Ignition",    "effect_type": "apply_burn",       "value": 0.01,
     "desc": "A spark rune. +1% chance to apply Burning on hit."},
    {"id": "rune_apply_stun",       "name": "Rune of Concussion",  "effect_type": "apply_stun",       "value": 0.01,
     "desc": "A skull-crack rune. +1% chance to apply Stunned on hit."},
    {"id": "rune_apply_chill",      "name": "Rune of Frostbite",   "effect_type": "apply_chill",      "value": 0.01,
     "desc": "An ice-shard rune. +1% chance to apply Chill on hit."},
    {"id": "rune_apply_fear",       "name": "Rune of Dread",       "effect_type": "apply_fear",       "value": 0.01,
     "desc": "A shadow-eye rune. +1% chance to apply Shaken on hit."},

    # --- Utility (1% each) ---
    {"id": "rune_gold_drop",        "name": "Rune of Greed",       "effect_type": "gold_drop",        "value": 0.01,
     "desc": "A coin-impressed rune. +1% Gold drop when socketed."},
    {"id": "rune_item_drop",        "name": "Rune of Fortune",     "effect_type": "item_drop",        "value": 0.01,
     "desc": "A clover rune. +1% Item drop chance when socketed."},
    {"id": "rune_rare_drop",        "name": "Rune of Rarity",      "effect_type": "rare_drop",        "value": 0.01,
     "desc": "A starfall rune. +1% Rare item drop chance when socketed."},
    {"id": "rune_xp_bonus",         "name": "Rune of Learning",    "effect_type": "xp_bonus",         "value": 0.01,
     "desc": "A book rune. +1% XP gain when socketed."},
    {"id": "rune_gathering",        "name": "Rune of Harvest",     "effect_type": "gathering_yield",  "value": 0.01,
     "desc": "A wheat-stalk rune. +1% Gathering yield when socketed."},
    {"id": "rune_crafting",         "name": "Rune of Smithing",    "effect_type": "crafting_quality", "value": 0.01,
     "desc": "A hammer rune. +1% Crafting quality when socketed."},
    {"id": "rune_heal_amp",         "name": "Rune of Restoration", "effect_type": "heal_amp",         "value": 0.01,
     "desc": "A chalice rune. +1% Healing received when socketed."},
    {"id": "rune_barrier_amp",      "name": "Rune of Shielding",   "effect_type": "barrier_amp",      "value": 0.01,
     "desc": "A dome rune. +1% Barrier strength when socketed."},
    {"id": "rune_status_duration",  "name": "Rune of Persistence", "effect_type": "status_duration",  "value": 0.01,
     "desc": "An hourglass rune. +1% Status duration on enemies when socketed."},
    {"id": "rune_cooldown_reduce",  "name": "Rune of Alacrity",    "effect_type": "cooldown_reduce",  "value": 0.01,
     "desc": "A lightning rune. +1% Cooldown reduction when socketed."},
    {"id": "rune_mp_cost_reduce",   "name": "Rune of Efficiency",  "effect_type": "mp_cost_reduce",   "value": 0.01,
     "desc": "A feather rune. +1% MP cost reduction when socketed."},
    {"id": "rune_stamina_cost_reduce","name": "Rune of Conservation","effect_type": "stamina_cost_reduce","value": 0.01,
     "desc": "A leaf rune. +1% Stamina cost reduction when socketed."},

    # --- Skill-Related (1% each) ---
    {"id": "rune_skill_damage",     "name": "Rune of Power",       "effect_type": "skill_damage",     "value": 0.01,
     "desc": "A fist rune. +1% Skill damage when socketed."},
    {"id": "rune_skill_healing",    "name": "Rune of Mending",     "effect_type": "skill_healing",    "value": 0.01,
     "desc": "A hand rune. +1% Skill healing when socketed."},
    {"id": "rune_counter_chance",   "name": "Rune of Retaliation", "effect_type": "counter_chance",   "value": 0.01,
     "desc": "A crossed-sword rune. +1% Counter-attack chance when socketed."},
    {"id": "rune_first_strike",     "name": "Rune of Initiative",  "effect_type": "first_strike",     "value": 0.01,
     "desc": "A lightning-strike rune. +1% First strike chance when socketed."},
    {"id": "rune_combo_gain",       "name": "Rune of Flow",        "effect_type": "combo_gain",       "value": 0.01,
     "desc": "A wave rune. +1% Combo point gain when socketed."},
]

RUNES_BY_ID: dict[str, dict] = {r["id"]: r for r in RUNES}
